# Generated by Django 4.2.17 on 2026-05-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_add_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_type', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('weights_path', models.CharField(help_text='Relative path from project root, e.g. models/mandalina/v1/weights.pt', max_length=500)),
                ('framework', models.CharField(default='YOLOv7', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detection_model_versions',
                'ordering': ['fruit_type', '-created_at'],
                'unique_together': {('fruit_type', 'version')},
            },
        ),
    ]
