# Generated by Django 4.2.17 on 2026-09-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_seed_model_versions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiDetectionBatch',
        ),
    ]
