# Generated by Django 4.2.17 on 2026-09-10 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0013_delete_multidetectionbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detection_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
