# Generated by Django 4.2.17 on 2026-05-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dron_map', '0006_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='field_polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon ring [[lng, lat], ...] defining the field boundary', null=True),
        ),
        migrations.CreateModel(
            name='SatelliteNDVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mean_ndvi', models.FloatField()),
                ('min_ndvi', models.FloatField()),
                ('max_ndvi', models.FloatField()),
                ('std_ndvi', models.FloatField()),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('scene_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_readings', to='dron_map.projects')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
